name: Release 🚢

on:
  push:
    tags:
      - "v*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release the extension
        uses: cli/gh-extension-precompile@v1.2.1
        with:
          go_version: "1.18.3"
